### ISSUE TITLE
Doesnt dowk "Atop is not a package"

### ISSUE THREAD

**Issue by elliot2dev** [aaarghhh/a_TON_of_privacy#1]
`root@chamoisee-sagenite:~/a_TON_of_privacy/src/atop# python3 atop.py 
Traceback (most recent call last):
  File "/root/a_TON_of_privacy/src/atop/atop.py", line 11, in <module>
    from atop.modules.telegramhelper import TelegramHelper
  File "/root/a_TON_of_privacy/src/atop/atop.py", line 11, in <module>
    from atop.modules.telegramhelper import TelegramHelper
ModuleNotFoundError: No module named 'atop.modules'; 'atop' is not a package
`

How to fix that?

**Comment by aaarghhh** [comment]
Hi, 
you can run it from sources.
```
# cd src/
# python -m atop.atop --target @whatiamlookingfor
```
Or using directly from commandline via pipx. 
```
# a-ton-of-privacy --target @whatiamlookingfor
```
